let ShopItemData =[{
    id:"dhaka",
    name:"casual shirt",
    price:50,
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img:"image/pexels-photo-227288.jpeg",
},
    {
        id:"dhakaa",
        name:"office shirt",
        price:55,
        desc:"Lore ipsum dolor sit amet, consectetur adipisicing.",
        img:"image/pexels-photo-769728.jpeg",
    },
    {
        id:"dhakab",
        name:"Man shirt",
        price:58,
        desc:"L ipsum dolor sit amet, consectetur adipisicing.",
        img:"image/pexels-photo-2313192.jpeg",
    },
    {
        id:"dhakab9",
        name:"women shirt",
        price:60,
        desc:"L ipsum dolor sit amet, consectetur adipisicing.",
        img:"image/photo-1598033129183-c4f50c736f10.avif",
    },
    {
        id:"dhakab2",
        name:"Cute shirt",
        price:70,
        desc:"L ipsum dolor sit amet, consectetur adipisicing.",
        img:"image/photo-1593757107729-eae8bcc74f8e.avif",
    },
    {
        id:"dhakabo",
        name:"women",
        price:80,
        desc:"L ipsum dolor sit amet, consectetur adipisicing.",
        img:"image/photo-1548864789-7393f2b4baa5.avif",
    },
    {
        id:"dhakabp",
        name:"boy shirt",
        price:90,
        desc:"L ipsum dolor sit amet, consectetur adipisicing.",
        img:"image/photo-1548778943-5bbeeb1ba6c1.avif",
    },
    {
        id:"dhakac",
        name:"Baby shirt",
        price:57,
        desc:"Lorepsum dolor sit amet, consectetur adipisicing.",
        img:"image/pexels-photo-1042140.jpeg",
    }]